[tool.poetry]
name = "thin-controller"
version = "0.0.1"
description = "Control your EC2 instances with a FastAPI instance in Lambda"
authors = ["James Hogkinson <james@terminaloutcomes.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.115.5"
pydantic = "^2.9.2"
mangum = "^0.19.0"
boto3 = "^1.35.63"
pydantic-settings = "^2.6.1"
uvicorn = "^0.32.0"
loguru = "^0.7.2"
python-multipart = "^0.0.17"


[tool.poetry.scripts]
"thin-controller" = "thin_controller.__main__:cli"

[tool.poetry.group.dev.dependencies]
ruff = "^0.7.4"
mypy = "^1.13.0"
pytest = "^8.3.3"
types-boto3 = "^1.0.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pylint.MASTER]
max-line-length = 200

# https://github.com/samuelcolvin/pydantic/issues/1961#issuecomment-759522422
#extension-pkg-whitelist=pydantic
#load-plugins=pylint_pydantic


[tool.pytest.ini_options]
testpaths = ["tests"]
