---
name: pytest

"on":
  push:
    branches:
      - main
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - name: Running pytest
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          python -m pip install --quiet --no-cache-dir --upgrade uv
          uv run pytest
          uv run coverage run --source=thin_controller -m pytest
          uv run coveralls
